### ISSUE TITLE
Выполнение арифметической операции без наличия второго операнда

### ISSUE THREAD

**Issue by truenorthpaul** [Snez0K/Calculator#1]
Если ввести второй операнд, активируется кнопки получения результата. Если после этого очистить его при помощи кнопки `CE`, то кнопка получения результата останется активной. При нажатии на нее приложение завершается с ошибкой.

**Comment by PavelDubsky** [comment]
Ошибся репозиторием.

**Comment by Snez0K** [comment]
![image](https://user-images.githubusercontent.com/17159498/41170942-416e4d88-6b57-11e8-9a92-ec6c3f99740b.png)
